### ISSUE TITLE
Virtual URL demo seems to be broken

### ISSUE THREAD

**Issue by delapuente** [fxos-components/serviceworkerware#32]

**Comment by arcturus** [comment]
The demo section contains a middleware that defines virtual URLS,

```
worker.get('virtual/.', function(request, response) {
  var url = request.clone().url;

  var content = '<html><body>'
      + url + ' ' + Math.random()
      + '<br/><a href="/demo/index.html">index</a></body></html>';

  return Promise.resolve(new Response(content, {
    headers: {
      'Content-Type': 'text/html'
    }
  }));
});
```
When running the demo via `gulp webserver` and accessing: `http://localhost:8000/demo/virtual/xyz` we get a 404 instead of an autogenerated page with the content coming from that middleware.

My first though is that it should get updated with the decorator `endWith` but we will need to investigate.

**Comment by humphd** [comment]
I'm not sure if what I'm seeing is the same, but for sure the demo is broken.  I'm seeing the following error:

```
Console: {"lineNumber":48,"message":"Uncaught (in promise) TypeError: Failed to execute 'append' on 'Headers': Headers are immutable","message_level":3,"sourceIdentifier":1,"sourceURL":"http://localhost:8000/demo/sw.js"}
Console: {"lineNumber":405,"message":"TypeError: Failed to fetch","message_level":3,"sourceIdentifier":3,"sourceURL":"http://localhost:8000/dist/sww.js"}
Console: {"lineNumber":0,"message":"The FetchEvent for \"http://localhost:8000/demo/index.html\" resulted in a network error response: the promise was rejected.","message_level":2,"sourceIdentifier":1,"sourceURL":""}
Console: {"lineNumber":0,"message":"Uncaught (in promise) TypeError: Failed to fetch","message_level":3,"sourceIdentifier":1,"sourceURL":""}
```

I assume that the `Request` needs to get copied vs. altered per http://stackoverflow.com/questions/35420980/how-to-alter-the-headers-of-a-request.

**Comment by humphd** [comment]
Wrong link, see http://stackoverflow.com/questions/35421179/how-to-alter-the-headers-of-a-response

**Comment by humphd** [comment]
@arcturus debugging your route, I notice that you're using `'virtual/.'` vs. `'virtual/*'`.  This will work for a URL like `http://localhost:8000/demo/virtual/x` but not `http://localhost:8000/demo/virtual/xyz` (i.e., `.` will match a single character after the `/` vs. anything).

I was able to get things running by commenting out the code that's altering the response headers, and using `'virtual/*'`.
