### ISSUE TITLE
Build script has debug statements

### ISSUE THREAD

**Issue by gmarty** [fxos-components/serviceworkerware#48]
Some debug statements are still present in the build script.
Is that expected?

**Comment by delapuente** [comment]
Sorry, what do you refer?

**Comment by gmarty** [comment]
Compare
https://github.com/fxos-components/serviceworkerware/blob/master/dist/sww.js#L175
and
https://github.com/fxos-components/serviceworkerware/blob/master/dist/sww.js#L307

`ServiceWorkerWare` has debug on while `SimpleOfflineCache` has debug off.
I think debug should be turned off in both classes.

What do you think?

**Comment by arcturus** [comment]
That's a great point and taking into account that we the preprocessor:
https://github.com/fxos-components/serviceworkerware/blob/master/lib/sww.js#L5-L7

wondering if we should write the debug statements in the following way:
```javascript
var debug = function(){};
// @ifdef DEBUG
debug = console.log.bind(console, '[ServiceWorkerWare]');
// @endif
```

@delapuente thoughts?

**Comment by delapuente** [comment]
Wow. That's a nice catch @gmarty. And yes @arcturus, considering we added _conditional compilation_ to the build process it seems the more reasonable way to do it. But I would isolate the debug to be only inside sww and not inside each middleware.
